### ISSUE TITLE
fg command not working

### ISSUE THREAD

**Issue by melchor629** [M8anu/MiShellObama#1]
fg command stucks the shell

**Steps to reproduce**
  1. `xeyes &`
  2. `fg`
  3. Shell is not working anymore

It has something to do with this code https://github.com/M8anu/MiShellObama/blob/master/AddInternalCommand.c#L128 Maybe the `block_SIGCHLD` must not be set during the wait or `set_terminal` must be set in other place.

**Comment by melchor629** [comment]
The issue is related to the `a b s e n c e` of an `get_item_bypos`.

**Comment by M8anu** [comment]
The error is produced by bg process, the fg just works nice, try: 
xeyes
Ctrl+Z
jobs
fg
*watch if eyes move xD*
