### ISSUE TITLE
bg says that the process has died

### ISSUE THREAD

**Issue by melchor629** [M8anu/MiShellObama#2]
Steps to reproduce:
  1. `xeyes`
  2. Ctrl+Z
  3. `bg`
  4. See that `xeyes` has died.

Seems that in the handler, CONTINUED is not processed so it says that `xeyes` has died instead of saying that is in background.

**Comment by melchor629** [comment]
**UPDATE**: Now it only occurs when `bg` is used. Maybe changing that `else` with `else if(status_res == EXITED || status_res == SIGNALED)` in https://github.com/M8anu/MiShellObama/blob/master/Shell_project.c#L163 does the trick. That is, checking that the process, in fact, has exited.

**Comment by M8anu** [comment]
Solved changing logical conditioners
